export const profiles = [
  {
    id: 1,
    name: 'Ximena Gutierrez',
    age: 23,
    location: 'Ciudad Tolima',
    height: 'Altura 172',
    image: '/placeholder.svg?height=300&width=250',
    description:
      'Lorem es una palabra de relleno común que se usa en diseño gráfico y web, especialmente en demostraciones de tipografías o borradores d...',
    featured: false,
    verified: true,
    online: true,
    hasVideo: false,
  },
  {
    id: 2,
    name: 'Jane Ximena',
    age: 23,
    location: 'Ciudad Huila',
    height: 'Altura 173',
    image: '/placeholder.svg?height=300&width=250',
    description:
      "Lorem ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since th...",
    featured: true,
    verified: true,
    online: false,
    hasVideo: true,
  },
  {
    id: 3,
    name: 'Sofia Martinez',
    age: 25,
    location: 'Ciudad Bogotá',
    height: 'Altura 168',
    image: '/placeholder.svg?height=300&width=250',
    description:
      'Profesional y elegante, ofrezco compañía de alta calidad para eventos sociales y cenas de negocios...',
    featured: false,
    verified: true,
    online: true,
    hasVideo: true,
  },
  {
    id: 4,
    name: 'Isabella Rodriguez',
    age: 24,
    location: 'Ciudad Medellín',
    height: 'Altura 170',
    image: '/placeholder.svg?height=300&width=250',
    description:
      'Experiencia única y personalizada. Disponible para acompañamiento en eventos especiales...',
    featured: true,
    verified: false,
    online: true,
    hasVideo: false,
  },
];
