export const categories = [
  { id: 'escort', label: 'ESCORT', active: true },
  { id: 'gigolo', label: 'GIGOLO' },
  { id: 'trans', label: 'TRANS' },
  { id: 'virtual', label: 'VIRTUAL' },
  { id: 'escort-gay', label: 'ESCORT GAY' },
  { id: 'masajistas', label: 'MASAJISTAS' },
];

export const stories = [
  {
    id: 1,
    user: 'Sofia Martinez',
    avatar: '/placeholder.svg?height=60&width=60',
    hasNew: true,
    timestamp: '2h',
  },
  {
    id: 2,
    user: 'Isabella Rodriguez',
    avatar: '/placeholder.svg?height=60&width=60',
    hasNew: true,
    timestamp: '4h',
  },
  {
    id: 3,
    user: 'Camila Torres',
    avatar: '/placeholder.svg?height=60&width=60',
    hasNew: false,
    timestamp: '1d',
  },
];

export const featuredProfiles = [
  {
    id: 1,
    name: 'Valentina Cruz',
    age: 24,
    location: 'Bogotá',
    image: '/placeholder.svg?height=400&width=300',
    verified: true,
    online: true,
    featured: true,
    rating: 4.9,
    reviews: 127,
  },
  {
    id: 2,
    name: 'Daniela Morales',
    age: 26,
    location: 'Medellín',
    image: '/placeholder.svg?height=400&width=300',
    verified: true,
    online: false,
    featured: true,
    rating: 4.8,
    reviews: 89,
  },
  {
    id: 3,
    name: 'Andrea Silva',
    age: 23,
    location: 'Cali',
    image: '/placeholder.svg?height=400&width=300',
    verified: true,
    online: true,
    featured: true,
    rating: 4.9,
    reviews: 156,
  },
  {
    id: 4,
    name: 'Natalia Vargas',
    age: 25,
    location: 'Cartagena',
    image: '/placeholder.svg?height=400&width=300',
    verified: true,
    online: true,
    featured: true,
    rating: 4.7,
    reviews: 98,
  },
];

export const userProfiles = [
  {
    id: 1,
    name: 'Jane Ximena',
    age: 23,
    category: 'ESCORT',
    location: 'Bogotá',
    image: '/placeholder.svg?height=200&width=200',
    views: '5.1k',
    rating: 4.9,
    status: 'Activo',
    verified: true,
    featured: true,
    completeness: 95,
  },
  {
    id: 2,
    name: 'Sofia Martinez',
    age: 25,
    category: 'ESCORT',
    location: 'Medellín',
    image: '/placeholder.svg?height=200&width=200',
    views: '3.8k',
    rating: 4.7,
    status: 'Activo',
    verified: true,
    featured: false,
    completeness: 78,
  },
  {
    id: 3,
    name: 'Isabella Rodriguez',
    age: 24,
    category: 'VIRTUAL',
    location: 'Cali',
    image: '/placeholder.svg?height=200&width=200',
    views: '2.9k',
    rating: 4.8,
    status: 'Pausado',
    verified: true,
    featured: true,
    completeness: 65,
  },
  {
    id: 4,
    name: 'Camila Torres',
    age: 26,
    category: 'ESCORT',
    location: 'Cartagena',
    image: '/placeholder.svg?height=200&width=200',
    views: '4.2k',
    rating: 4.6,
    status: 'Activo',
    verified: false,
    featured: false,
    completeness: 45,
  },
  {
    id: 5,
    name: 'Valentina Cruz',
    age: 22,
    category: 'VIRTUAL',
    location: 'Barranquilla',
    image: '/placeholder.svg?height=200&width=200',
    views: '3.1k',
    rating: 4.5,
    status: 'Activo',
    verified: true,
    featured: false,
    completeness: 82,
  },
  {
    id: 6,
    name: 'Andrea Silva',
    age: 27,
    category: 'ESCORT',
    location: 'Pereira',
    image: '/placeholder.svg?height=200&width=200',
    views: '2.7k',
    rating: 4.4,
    status: 'Activo',
    verified: true,
    featured: false,
    completeness: 91,
  },
];

export const paymentHistoryData = [
  {
    id: 1,
    date: '2024-12-15',
    description: 'Pago por servicios premium',
    amount: 250.0,
    status: 'Completado',
    method: 'Tarjeta de crédito',
  },
  {
    id: 2,
    date: '2024-12-10',
    description: 'Impulso de perfil - Jane Ximena',
    amount: 75.0,
    status: 'Completado',
    method: 'PayPal',
  },
  {
    id: 3,
    date: '2024-12-05',
    description: 'Suscripción mensual',
    amount: 150.0,
    status: 'Completado',
    method: 'Transferencia bancaria',
  },
  {
    id: 4,
    date: '2024-11-28',
    description: 'Destacar perfil - Sofia Martinez',
    amount: 50.0,
    status: 'Pendiente',
    method: 'Tarjeta de débito',
  },
  {
    id: 5,
    date: '2024-11-20',
    description: 'Pago por servicios adicionales',
    amount: 125.0,
    status: 'Completado',
    method: 'Tarjeta de crédito',
  },
];
