export const profileData = {
  id: '1',
  name: 'Jane Ximena',
  age: 23,
  location: 'Colombia, Huila',
  category: 'ESCORT',
  verified: true,
  online: true,
  rating: 4.9,
  reviews: 127,
  images: [
    '/placeholder.svg?height=400&width=600',
    '/placeholder.svg?height=400&width=400',
    '/placeholder.svg?height=400&width=400',
    '/placeholder.svg?height=400&width=600',
    '/placeholder.svg?height=400&width=400',
    '/placeholder.svg?height=400&width=400',
  ],
  description:
    'Hola, soy Jane, una acompañante profesional y elegante. Me caracterizo por mi personalidad carismática y mi dedicación a brindar momentos únicos e inolvidables. Disfruto de las conversaciones interesantes, las cenas elegantes y los eventos sociales. Mi objetivo es hacer que cada encuentro sea especial y memorable.',
  services: [
    'Acompañamiento a eventos sociales',
    'Cenas románticas',
    'Compañía para viajes',
    'Conversaciones intelectuales',
    'Masajes relajantes',
    'Experiencias personalizadas',
  ],
  physicalTraits: {
    edad: '23',
    piel: 'Blanca',
    genero: 'Mujer',
    ubicacion: 'Colombia, Huila',
    ojos: 'Negros',
    pelo: 'Negro',
    cuerpo: 'Curvy',
    altura: '173 cm',
    busto: 'COPA_D',
  },
  socialMedia: {
    whatsapp: '+57 300 123 4567',
    telegram: '@janeximena',
    instagram: '@jane.ximena',
    twitter: '@janeximena',
    facebook: 'jane.ximena',
  },
  rates: [
    { duration: '1 hora', price: 200, currency: 'USD' },
    { duration: '2 horas', price: 350, currency: 'USD' },
    { duration: 'Noche completa', price: 800, currency: 'USD' },
    { duration: 'Fin de semana', price: 1500, currency: 'USD' },
  ],
  availability: {
    monday: '9:00 AM - 11:00 PM',
    tuesday: '9:00 AM - 11:00 PM',
    wednesday: '9:00 AM - 11:00 PM',
    thursday: '9:00 AM - 11:00 PM',
    friday: '24 horas',
    saturday: '24 horas',
    sunday: '2:00 PM - 10:00 PM',
  },
  videoUrl: '/placeholder-video.mp4',
};
